font_family      JetBrains Mono
bold_font         JetBrains Mono Bold
italic_font       JetBrains Mono Italic
font_size        11.0

scrollback_lines 10000
scrollback_pager less --chop-long-lines +G

sync_to_monitor no
repaint_delay 2
input_delay 1

background_opacity 0.95
hide_window_decorations yes
confirm_os_window_close 0

map ctrl+shift+t new_tab
map ctrl+shift+q close_tab
map ctrl+shift+enter new_window
map ctrl+shift+right next_tab
map ctrl+shift+left previous_tab

include theme.conf

linux_display_server wayland
