$mainMod = SUPER

source = ~/.config/hypr/monitors/single-eDP.conf
source = ~/.config/hypr/binds/default.conf

exec-once = waybar & dunst & hyprpaper & polkit-gnome-authentication-agent-1 & wl-clipboard

env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = QT_QPA_PLATFORM,wayland;xcb
env = GDK_BACKEND,wayland,x11
env = _JAVA_AWT_WM_NONREPARENTING,1
env = NIXOS_OZONE_WL,1

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(89b4faff)
    col.inactive_border = rgba(45475aff)
    cursor_inactive_timeout = 5
    no_focus_fallback = false
}

decoration {
    rounding = 10
    border_size = 2
    border_plus_passing = yes
    blur {
        enabled = yes
        size = 5
        passes = 3
        noise = 0.1
        contrast = 0.8
        brightness = 0.9
        popups = true
    }
    shadow {
        enabled = yes
        range = 20
        render_power = 3
        color = rgba(0, 0, 0, 0.8)
    }
}

animations {
    enabled = yes
    bezier = wind, 0.05, 0.9, 0.1, 1.05
    bezier = overshot, 0.13, 0.99, 0.29, 1.1
    bezier = linear, 0.0, 0.0, 1.0, 1.0
    animation = windows, 1, 7, wind, slide
    animation = windowsOut, 1, 7, wind, slide
    animation = fade, 1, 5, linear
    animation = workspaces, 1, 6, overshot, slide
    animation = specialWorkspace, 1, 6, overshot, slidevert
    animation = border, 1, 10, default
}

input {
    kb_layout = es
    kb_variant =
    kb_model =
    kb_options = ctrl:nocaps
    numlock_by_default = true
    follow_mouse = 1
    mouse_refocus = false
    touchpad {
        natural_scroll = yes
        tap-to-click = yes
        drag_lock = yes
        disable_while_typing = true
        clickfinger_behavior = yes
    }
    tablet {
        output = eDP-1
    }
}

master {
    new_status = master
    orientation = left
    smart_gaps = false
    mfact = 0.55
}

windowrule = float, title:^(Calculator)$
windowrule = float, title:^(Picture-in-Picture)$
windowrule = opacity 0.9 0.9, class:^(kitty)$
windowrule = noanim, class:^(rofi)$
windowrule = noblur, class:^(rofi)$
windowrule = nomaxsize, class:^(Steam)$
windowrule = fullscreen, class:^(gamescope)$
